version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: BDD_SISTEMA_BANCARIO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8080:8080"
    restart: always
volumes:
  db_data: